### ISSUE TITLE
Review Mother/Child relationship model

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-childhealth#1]
review general model representation
question:  we can use this for other relationships such as as adoptive mother; father etc - should we have a general parent, child model with suitable relationship  type value set or have specific birth mother + add other types of relationships elsewhere?

**Comment by shovanroy-github** [comment]
As per current profile, the details of the mother, father and other are captured using Patient.contact. A single Patient profile has been drafted with providing example of how the baby Patient and mother Patient will look like. No separate profile for father has been drafted.
