### ISSUE TITLE
(Tympanometry)  Screen representation

### ISSUE THREAD

**Issue by brettesler-ext** [hl7au/au-fhir-childhealth#2]
(Tympanometry)  Screen is defined as codes Category A, Category B, Category C but in 
http://build.fhir.org/ig/hl7au/au-fhir-childhealth/StructureDefinition-ncdhc-observation-hearing-check.html 
is apperaing as an interpretation valueset
 http://build.fhir.org/ig/hl7au/au-fhir-childhealth/ValueSet-ncdhc-observation-interpretation.html

**Comment by shovanroy-github** [comment]
Fixed and latest version published
