### ISSUE TITLE
Bug: Naming Issue on Profile - Expected Mother

### ISSUE THREAD

**Issue by oliver-krauss** [hl7au/au-fhir-childhealth#4]
Reporter: Oliver Krauss
Actual Reporter: Elizabeth Donhoo
Severity: Typo
Link: http://build.fhir.org/ig/hl7au/au-fhir-childhealth/StructureDefinition-ncdhc-patient-mother.html

This should probably be "Expectant Mother"

**Comment by shovanroy-github** [comment]
Fixed and Deployed
